name: "Build DB"
description: "Compiles separate files into one json file"
inputs:
  GITHUB_TOKEN:
    description: "GitHub token for authentication"
    required: true
runs:
  using: "node16"
  main: "buildDB.js"

  

